export const SITE = {
  name: "Xtreme Collision",
  url: "https://www.xtremecollision.com",
  title: "Xtreme Collision | 5-Star Auto Body & Collision Repair in North Texas",
  description:
    "Expert collision repair in Carrollton, TX. Xtreme Collision works with all major insurance companies, offers a lifetime limited warranty, and repairs vehicles to factory standards.",
  phone: "(469) 887-4815",
  phoneHref: "tel:+14698874815",
  address: "2025 Midway Road, Suite E, Carrollton, TX 75006",
  areas: "Carrollton, Addison, Dallas, Plano, Frisco, Richardson",
  city: "Carrollton",
  region: "TX",
  postalCode: "75006",
  country: "US",
  coordinates: {
    latitude: 32.9539,
    longitude: -96.8394,
  },
  services: [
    "Collision repair",
    "Hail damage repair",
    "Paintless dent repair",
    "Dent and scratch repair",
    "Insurance claims assistance",
    "Frame repair",
    "Unibody repair",
    "Computerized frame measuring",
    "Electrical wiring repair",
    "Steering and suspension repair",
    "Rental car coordination",
    "Sherwin Williams certified color matching",
  ],
  socials: [
    { name: "Facebook", href: "https://www.facebook.com/XtremeCollisionRepair" },
    { name: "Instagram", href: "https://www.instagram.com/xtreme_collision/" },
    { name: "Yelp", href: "https://www.yelp.com/biz/xtreme-collision-repair-carrollton" },
  ],
  hours: [
    { day: "Mon", time: "8:00am - 5:30pm" },
    { day: "Tue", time: "8:00am - 5:30pm" },
    { day: "Wed", time: "8:00am - 5:30pm" },
    { day: "Thu", time: "8:00am - 5:30pm" },
    { day: "Fri", time: "8:00am - 12:00pm" },
    { day: "Sat", time: "Closed" },
    { day: "Sun", time: "Closed" },
  ],
} as const
